name: python-build
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    #environment: 'dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SetUp Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Files
        run: sudo ls -lrth /home/runner/work/pythonproject/pythonproject/src/
      - name: Create folder
        run: |
              sudo mkdir /home/artifacts/
              sudo chmod 777 /home/artifacts/
              sudo cp -r src/* /home/artifacts/
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Python-artifacts
          path: /home/artifacts/
      - name: Artifacts Files
        run: sudo ls -lrth /home/
